### ISSUE TITLE
As a data manager I need to know whether the dmp was approved (e.g. by the management) so that I can proceed with the required next steps

### ISSUE THREAD

**Issue by jludwig1** [RDA-DMP-Common/user-stories#37]

**Comment by jludwig1** [comment]
Would you regard it as in scope if we rephrase it as information about the approval of the dmp? I think this is similar to recording when a DMP was updated.

**Comment by TomMiksa** [comment]
Ok, that makes sense to me. Usually when we put a user story into out of scope, it was because they were describing some process around the DMPs or were expressing motivation for what we're doing. The main focus of our consultation is to find out what topics have to be modelled. After your explanation I can imagine a specific field in the model.
