### ISSUE TITLE
As the Director of Research Integrity I want researchers to classify research data according to the institutional Data Classification Standard so that they can align plans for managing and curating the data with requirements of the Standard 

### ISSUE THREAD

**Issue by maudefrances** [RDA-DMP-Common/user-stories#47]

**Comment by paulwalk** [comment]
This is on the borderline of being out of scope.... need a second opinion

**Comment by TomMiksa** [comment]
I think this may be just the problem of how the user story is phrased - other stories from this user are formulated similarly. 
It would rewrite it like this: As an instiution, I want researchers to follow metadata standards recommended by my inistitution, so that data produced by our researchers is described following the same standard.

**Comment by peterneish** [comment]
I think it is a bit more than that. How about:  As an institution, I want researchers to follow an institutional standard when classifying data so that data can be managed and curated consistently.

**Comment by maudefrances** [comment]
Thanks Peter,
This is a real use case at UNSW. The RDMP is used as a tool for classifying research data. Classification levels, ranging from ‘top secret’ to ‘public’ are used to determine how and where data can be stored and what research/analysis tools can be used.
Maude.

Sent from my iPad

On 1 Feb 2018, at 8:56 pm, Peter Neish <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it is a bit more than that. How about: As an institution, I want researchers to follow an institutional standard when classifying data so that data can be managed and curated consistently.
