### ISSUE TITLE
As a researcher, I want to indicate where my data will be stored during the project and where after the project, so that it remains accessible during all stages of the data lifecycle.

### ISSUE THREAD

**Issue by TomMiksa** [RDA-DMP-Common/user-stories#60]
Based on the workshop outputs: https://doi.org/10.5281/zenodo.1067753

**Comment by paulwalk** [comment]
seconded.

**Comment by TomMiksa** [comment]
I think it describes well the need for automation and for the PROCESS, but not for the MODEL. 
I would suggest to put it into out of scope.

**Comment by paulwalk** [comment]
agreed. It is a requirement for information and/or support outside of the DMP itself

**Comment by jludwig1** [comment]
I have not a complete overview, but using the search I couldn’t find a user story about where the data is or will be stored. Obviously a reference to the data should be part of a DMP. If there is no user story for a data storage location I suggest that we slightly rephrase this one.

**Comment by TomMiksa** [comment]
The problem here was that the story sounds as if the DMP was supposed to know where a researcher is going to store data. The recommender system can provide tips, but the researcher has to select. Whatever they select goes into a DMP. That's why this user story was rejected.

We can rewrite this user strory:
As a researcher, I want to INDICATE where to store my data (?? DURING THE PROJECT / AFTER THE PROJECT ??), so that it remains saved and accessible.

**Comment by jludwig1** [comment]
I think it is during _and_ after the project. During the project the data is probably stored in internal or shared storage locations and the information might be useful for partners and support staff/data managers. After the project the data will (hopefully) be stored in a public repository and the information in the DMP will be useful for funders, reviewers etc.

What about: As a researcher, I want to indicate where my data will be stored during the project and where after the project, so that it remains accessible during all stages of the data lifecycle.
